# Generated by Django 5.2.10 on 2026-02-02 15:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('order', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_registration', models.BooleanField(default=True, help_text='Allow new users to register on the site')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6B7280', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('habit_type', models.CharField(choices=[('boolean', 'Yes/No'), ('counter', 'Counter'), ('value', 'Decimal Value'), ('rating', 'Rating')], default='boolean', max_length=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('icon', models.CharField(default='calendar', max_length=50)),
                ('color', models.CharField(default='#1F85DE', max_length=20)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, help_text="Optional unit for value habit (e.g., 'km', 'miles', 'hours')", max_length=50, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to='app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='habits', to='app.tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='app.habit')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HabitCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pearson_coefficient', models.DecimalField(blank=True, decimal_places=4, help_text='Pearson correlation (linear relationships)', max_digits=5, null=True)),
                ('spearman_coefficient', models.DecimalField(blank=True, decimal_places=4, help_text='Spearman rank correlation (handles ordinal data better)', max_digits=5, null=True)),
                ('dtw_distance', models.DecimalField(blank=True, decimal_places=4, help_text='Dynamic Time Warping distance (detects time-shifted patterns)', max_digits=5, null=True)),
                ('sample_size', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('max_correlation', models.DecimalField(decimal_places=4, default=0, help_text='Maximum correlation strength across all methods (0-1)', max_digits=5)),
                ('habit1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations_as_habit1', to='app.habit')),
                ('habit2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations_as_habit2', to='app.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_correlations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-max_correlation'],
                'indexes': [models.Index(fields=['user', '-max_correlation'], name='app_habitco_user_id_6ec931_idx')],
                'unique_together': {('user', 'habit1', 'habit2')},
            },
        ),
    ]
